# Generated by Django 4.1.7 on 2023-11-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extrangería')], max_length=2, verbose_name='Tipo de Documento')),
                ('documento', models.PositiveIntegerField(unique=True, verbose_name='Documento')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefono', models.PositiveIntegerField(verbose_name='Teléfono')),
                ('ciudad', models.CharField(max_length=45, verbose_name='Ciudad')),
                ('direccion', models.CharField(max_length=45, verbose_name='Dirección')),
                ('email', models.CharField(max_length=45, verbose_name='Email')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
