# Generated by Django 4.2.7 on 2023-11-28 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_bodegaproducto_bodega_bodegaproducto_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='bodega',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
    ]
