# Generated by Django 4.2.7 on 2023-11-28 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_remove_producto_bodega_remove_producto_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.producto', verbose_name='Producto'),
        ),
    ]
